### ISSUE TITLE
Some queries about the operation

### ISSUE THREAD

**Issue by soumyamahunt** [hannesne/NamedPipesSample#1]
Will this work if uwp app is the client and win32 app is server while keeping the pipe names the same??

**Comment by hannesne** [comment]
It's unfortunately been a long time since I worked with this, but I believe it will.

**Comment by soumyamahunt** [comment]
> It's unfortunately been a long time since I worked with this, but I believe it will.

I tried to do that but it seems uwp app can't open pipes from win32 apps that way unless win32 apps sets the permission properly. [Here](https://stackoverflow.com/a/60452660/13225760) is more details about it.

Also, you can improve this sample to work without having to check in powershell for full pipe name. In uwp app get the package sid and store it in application data:
`Windows.Storage.ApplicationData.Current.LocalSettings.Values["PackageSid"] = WebAuthenticationBroker.GetCurrentApplicationCallbackUri().Host.ToUpper();`
In win32 process get the session id and retrieve the package sid:
`var namedPipeName=$"Sessions\\{Process.GetCurrentProcess().SessionId}\\AppContainerNamedObjects\\{Windows.Storage.ApplicationData.Current.LocalSettings.Values["PackageSid"]}\\mypipe";`
This will work even if for all app installation across all users.

**Comment by hannesne** [comment]
Would you mind submitting  PR on that, it seems like something that would help future devs?

**Comment by soumyamahunt** [comment]
> Would you mind submitting PR on that, it seems like something that would help future devs?

Submitted changes in #2.

**Comment by hannesne** [comment]
Thank you for the contribution!

**Comment by MoeexT** [comment]
This sample is so helpful! Thank you, bro!!!
